### ISSUE TITLE
Create init option (pass a MID)

### ISSUE THREAD

**Issue by taketin** [tic80hackathon/TIC-80#10]

**Comment by seisuke** [comment]
in index.html 
```
var Module = {canvas: document.getElementById('canvas')
            , arguments:['.', '-nosound']
 };
```
we can add uid option as key value option 
https://github.com/tic80hackathon/TIC-80/blob/stable/src/console.c#L3234

**Comment by taketin** [comment]
https://github.com/tic80hackathon/TIC-80/pull/12
